name: puss_puss
description: The purr-fect token for the purr-fect blockchain.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.1+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.0
  intl: ^0.19.0
  logger: ^2.0.2+1
  url_launcher: ^6.2.3

  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6
  google_nav_bar: ^5.0.6

  get: ^4.6.6
  get_storage: ^2.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true

assets:
    - assets/icons/
    - assets/images/
 

fonts:
  - family: NeueMontreal
    fonts:
      - asset: assets/fonts/NeueMontreal-Bold.otf
        weight: 700
      - asset: assets/fonts/NeueMontreal-Light.otf
        weight: 300
      - asset: assets/fonts/NeueMontreal-Medium.otf
        weight: 500
      - asset: assets/fonts/NeueMontreal-Regular.otf
        weight: 400