// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvx14KW2_sx6KtIvxP8hXZ_wm_ISu6N1c',
    appId: '1:917601657897:web:4cad2c1419749be69fe838',
    messagingSenderId: '917601657897',
    projectId: 'pusspuss-36652',
    authDomain: 'pusspuss-36652.firebaseapp.com',
    storageBucket: 'pusspuss-36652.appspot.com',
    measurementId: 'G-EB63083D6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPYlfC4ctz3sNbmeYPceYEA8WclOJD5e4',
    appId: '1:917601657897:android:3278c41f94e30ccd9fe838',
    messagingSenderId: '917601657897',
    projectId: 'pusspuss-36652',
    storageBucket: 'pusspuss-36652.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHIM73bscz1advRsJbO__rnxR4PEwf0w8',
    appId: '1:917601657897:ios:a0b01e4bdf34acd19fe838',
    messagingSenderId: '917601657897',
    projectId: 'pusspuss-36652',
    storageBucket: 'pusspuss-36652.appspot.com',
    androidClientId: '917601657897-971he3gklac2a5262il5gfc3d7kqi4g0.apps.googleusercontent.com',
    iosClientId: '917601657897-dkrjcol921cd3j8bljmk053f0a8f1nt9.apps.googleusercontent.com',
    iosBundleId: 'com.example.pussPuss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHIM73bscz1advRsJbO__rnxR4PEwf0w8',
    appId: '1:917601657897:ios:b81f6fbe0bf7f3669fe838',
    messagingSenderId: '917601657897',
    projectId: 'pusspuss-36652',
    storageBucket: 'pusspuss-36652.appspot.com',
    androidClientId: '917601657897-971he3gklac2a5262il5gfc3d7kqi4g0.apps.googleusercontent.com',
    iosClientId: '917601657897-7a6e3rb2j1ff9rvjphv8dr9hjkukdcef.apps.googleusercontent.com',
    iosBundleId: 'com.example.pussPuss.RunnerTests',
  );
}
